(define (make-account balance account-password invoked)
  (define (withdraw amount)
    (if (>= balance amount)
        (begin (set! balance 
                     (- balance amount))
               balance)
        "Insufficient funds"))
  (define (deposit amount)
    (set! balance (+ balance amount))
    balance)
  (define (dispatch m provided-password)
    (set! invoked (+ invoked 1))
    (cond ((> invoked 7)
	   (lambda (operation) "Cops were called"))
          ((not (eq? account-password provided-password))
	   (lambda (operation) "Incorrect password"))
      	  ((eq? m 'withdraw) withdraw)
          ((eq? m 'deposit) deposit)
          (else (error "Unknown request: 
                 MAKE-ACCOUNT" m))))
  dispatch)
